name: Publish to PyPI

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest -v

      - name: Get current version
        id: version
        run: |
          VERSION=$(poetry version -s)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set run title
        run: |
          gh api --method PATCH \
            /repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            -f display_title="Publish v${{ steps.version.outputs.version }} to pipy"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Build dist
        run: poetry build

      - name: Publish to PyPI
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
